### ISSUE TITLE
#/securityDefinitions/Oauth2_ClientCredentials' of type object did not match any of the required schemas

### ISSUE THREAD

**Issue by marcredhat** [3scale/3scale_toolbox#141]
When importing SAP OpenAPI specs s.a. http://bit.ly/2W3T3TJ, I get
Error: OpenAPI schema validation failed: The property '#/securityDefinitions/Oauth2_ClientCredentials' of type object did not match any of the required schemas

If I remove the security definitions, I can import without issues as shown below:
[marc@rhel8ga ~]$ 3scale -v
0.10.0

[marc@rhel8ga ~]$ 3scale import openapi -d https://<token>@<>-admin.3scale.net test.json --default-credentials-userkey=111
Updated service id: 2555417800952, name: Inference Service For Customizable Image Feature Extraction
destroying all mapping rules
Created POST /mlfs/api/v2/image/feature-extraction$ endpoint
Created POST /mlfs/api/v2/image/models/{modelName}/versions/{version}$ endpoint
Activedocs exists, update!
Service proxy updated

**Comment by eguzki** [comment]
If I am not wrong, your SAP spec does not fully comply with used [swagger json schema](https://github.com/OAI/OpenAPI-Specification/blob/master/schemas/v2.0/schema.json) in the toolbox.

Specifically the validation error occurs on `tokenUrl` field.

```yaml
Oauth2_ClientCredentials:                                                              
  type: oauth2                                                                         
  tokenUrl: https://{suffix}.authentication.{region}.hana.ondemand.com/oauth/token     
  flow: application                                                                    
  scopes: {}                                                                           
```

Json-schema for OpenApi 2.0 states:
```json
"tokenUrl": {        
  "type": "string",  
  "format": "uri"    
},        
```

`uri` format validator ([spec](https://json-schema.org/latest/json-schema-validation.html#rfc.section.7.3.5)) does not accept uri templates. There is a `uri-template` format validator, but openapi schema defines as `uri` instead of `uri-template`

Therefore, I see three feasible solutions to your issue, ordered by, IMO, most recommendable to the least recommendable solution:

1. Change your SAP spec and do not use uri templates, but valid URI
1. 3scale toolbox allows skipping json schema validation passing `--skip-openapi-validation` flag
1. 3scale Toolbox patches [public known swagger spec json schema](https://github.com/OAI/OpenAPI-Specification/blob/master/schemas/v2.0/schema.json), and allow uri templates on `tokenUrl` field
