### ISSUE TITLE
OIDC configuration while importing services from OpenAPI file

### ISSUE THREAD

**Issue by PoojaChandak** [3scale/3scale_toolbox#263]
The import command for APIs from an OpenAPI file can be provided with an option to configure the OpenID Connect Issuer. When we tried the same in realtime the authentication option did not change for this product. It remains as "API Key (user_key) The application is identified & authenticated via a single string". Hence, looks like the --openid-connect-issuer option isn't working as expected. Kindly check.

**Comment by PoojaChandak** [comment]
It is a confidential project set up for one of our clients. Sharing exact details might not be possible. 
However, to explain the scenario, the issue is as below:

We are able to connect 3scale with RHSSO from the 3scale admin portal while onboarding an API. 
Whereas, while importing the same API using its swagger file and providing the --openid-connect-issuer option in the 3scale import command, the authentication option is not updated. We can still see the authentication option to be API key. All other aspects like backend, product, and methods with mapping rules are created correctly.

**Comment by eguzki** [comment]
Please, open Jira issue and make it restricted to RH employee. Anyway, usually there is no confidential info in the security requirements and security definitions. That is why the toolbox adds extra param `--openid-connect-issuer` where confidential information lives and you can leave the OAS resource without sensitive data.

It should be something like this:

```
security:                                                                                 
- petstore_auth:                                                                          
  - 'write:pets'                                                                          
                                                                                          
securityDefinitions:                                                                      
  petstore_auth:                                                                          
    type: oauth2                                                                          
    authorizationUrl: 'https://petstore.swagger.io/oauth/authorize'                       
    flow: implicit                                                                        
    scopes:                                                                               
      'write:pets': modify pets in your account                                           
      'read:pets': read your pets                                                         
```
