### ISSUE TITLE
RFE: Command to export/import Application Plan limits, pricing rules and features

### ISSUE THREAD

**Issue by nmasse-itix** [3scale/3scale_toolbox#94]
# Current Situation

Currently, when importing a new service from an OpenAPI with:

```sh
3scale import openapi -t echo_api -d https://$ACCESS_TOKEN@$TENANT-admin.3scale.net examples/echo-api-oidc.yaml
```

The metrics / methods and mapping rules are created but the limits / pricing rules / features that compose an application plan are not created. 

# Proposed changes

A new command is introduced to **import** application plan artefacts from a YAML file. 

```sh
3scale import application-plan -p my_app_plan -t echo_api -f /path/to/app-plan.yaml -d https://$ACCESS_TOKEN@$TENANT-admin.3scale.net examples/echo-api-oidc.yaml
```

A new command is introduced to **export** application plan artefacts from a YAML file. 

```sh
3scale export application-plan -p my_app_plan -t echo_api -f /path/to/app-plan.yaml -d https://$ACCESS_TOKEN@$TENANT-admin.3scale.net examples/echo-api-oidc.yaml
```

# Usage in a CI/CD pipeline

Upon commit in the GIT repository, the CI/CD pipeline would : 
1. call the `3scale import openapi` command to create / update the service
2. call the `3scale import application-plan` command to create / update the application plans from the artefact file (if provided in the GIT repo)

If the limits / pricing rules are not in the hand of the developers (maybe something more in the hands of the product owner), the CI/CD pipeline would be configured to stop after the first environment if there is no artefact file, if it is not up-to-date or if the 3scale service has no up-to-date application plan. 

The product owner can connect to the 3scale tenant and fill-in the limits, pricing rules and features using the Web Interface. 

He then can re-launch the CI/CD pipeline and this time the CI/CD pipeline would export the application plan artefacts from the first env into a file using the `3scale export application-plan`, commit the file to the repo, and deploy the API in all the subsequent environments using:

1. call the `3scale import openapi` command to create / update the service
2. call the `3scale import application-plan` command to create / update the application plans from the artefact file

# Business justification

Currently, application plans are on the critical path to use an API (without them, the API is not usable). So the Application Plan deployment should be automated.

**Comment by nmasse-itix** [comment]
I forgot to add that it would be nice if we could use the same artefact file format as the 3scale operator. 👍

**Comment by eguzki** [comment]
Current spec for Application Plan Custom Resource. 
https://github.com/3scale/3scale-operator/blob/master/doc/api-crd-reference.md#planspec

Note api version: is in alpha `apiVersion: capabilities.3scale.net/v1alpha1`

**Comment by eguzki** [comment]
Using artifact file format as the 3scale operator can be valuable as a product since you are building a bridge between 3scale operator and toolbox interoperability. 

However, 3scale Operator CRD's are in alpha state and may be changed breaking backward compatibiliy. This is risky. We could define custom file format for the toolbox and avoid this issue, but then files would not be valid for the 3scale operator.

IMO, the risks are worth to be taken and we should go for the option of working with operator CRD compatible formats. So the proposal for the implementation of this issue is the following:

When importing/exporting plans/limits/features/pricingrules objects, the artifact file will actually be resource list file:

```yaml
apiVersion: v1
kind: List
items:
- apiVersion: capabilities.3scale.net/v1alpha1
  metadata:
    name: plan01
  kind: Plan
  spec:
    default: true
    approvalRequired: false
    costs:
      costMonth: 0
      setupFee: 0
    trialPeriod: 0
    limitSelector:
      matchLabels:
        plan: plan01
- apiVersion: capabilities.3scale.net/v1alpha1
  kind: Limit
  metadata:
    name: plan01-metric01-day-10
   labels:
     plan: plan01
  spec:
    description: Limit for metric01 in plan01
    maxValue: 10
    metricRef:
      name: metric01
    period: day
```




We can validate artifact files using openapi spec schema validator, using the same CRD openAPIV3Schema validator (for instance [app plan CRD schema](https://github.com/3scale/3scale-operator/blob/master/deploy/crds/capabilities_v1alpha1_plan_crd.yaml))

Note that Pricing Rules and Plan Features are not implemented yet in 3scale operator, so, we would need to advance design of their respective CRD's.

WDYT @mikz @miguelsorianod
